### ISSUE TITLE
Request for next update

### ISSUE THREAD

**Issue by kirk86** [AospExtended/official_devices#420]
Hi folks, 
thank you for you great job on maintaining and improving this custom rom.
I would like to request if possible for the next release to have a look at the following points:

- Battery (fast charging)
- Memory footprint
- Speed
- Thermals (temperature)

I've been running aosp on my oneplus 2 and have noticed so far the above minor issues.
The device turns quite hot sometimes especially when charging.
It seems that the longer I use the device and apps the memory footprint seems to be increasing even when I close all apps.
I'd also love for the collections button if it was faster when navigating or trying to close multiple open apps.
Overall speed of daily usage is ok but it wouldn't harm to be faster.

Thanks again for your service and keep up the good work.

Cheers!

**Comment by sb6596** [comment]
@kirk86 Oneplus2 is dying

**Comment by kirk86** [comment]
I know that's an old device, but there's still a large user base using it as daily drive, most probably not gamers. 
Specs wise its not worse than 2019 model, e.g. huawei p smart 2019.
So, I don't know if it's dying because is getting out of fashion or because it can't handle new OSes?
So far it plays really good with android 10, no major issues.
I'm confident that it can handle android 11 as well.

**Comment by sb6596** [comment]
@kirk86 msms8994 died when it was launched

**Comment by SakilMondal** [comment]
@sb6596 😂

**Comment by kirk86** [comment]
@sb6596 Could be for high end users, for my use-case works just fine.

**Comment by sb6596** [comment]
@kirk86 Its better you contact your device's official maintainer and discuss your issues with him. Closing this issue for now.
